blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:post_id>/', views.blogpost, name='blogpost'),
    path('<int:pk>/edit/', views.EditPostView.as_view(), name='edit'),
    path('new/', views.NewPostView.as_view(), name='new'),
    path('<int:post_id>/change/', views.change, name='change'),
    path('create/', views.create, name='create'),
    path('search_results/', views.search_results, name='search_results'),
    path('myposts/', views.OwnedPostsByUserView.as_view(), name='myposts'),
    path('mycomments/', views.OwnedCommentsByUserView.as_view(), name='mycomments'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/deleted/', views.deleted, name='deleted'),
    path('<int:comment_id>/editcomment/', views.edit_comment, name='editcomment'),
    path('<int:comment_id>/deletedcomment/', views.deleted_comment, name='deletedcomment'),
    
    
]

collector/urls.py
from django.urls import path

from . import views

app_name = "collector"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:card_id>/', views.card, name='card'),
    path('buy_card/<int:card_id>', views.buy_card, name="buy_card"),
    path('buy_pack/', views.buy_pack, name="buy_pack"),
    path('search_results/', views.search_results, name="search_results"),
    path('my_collection/', views.my_collection, name="my_collection"),
    path('new_card/', views.NewCardView.as_view(), name="new_card"),
    path('create/', views.create, name='create'),
    path('collect/', views.collect, name="collect"),
]

mysite/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin

app_name = "polls"
urlpatterns = [
    path('', include("blog.urls")),
    path('polls/', include("polls.urls")),
    path('collector/', include("collector.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

collector/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Card(models.Model):
    COMMON = "C"
    RARE = "R"
    EPIC = "E"
    LEGENDARY = "L"
    RARITY_CHOICES = (
        (COMMON, "Common"),
        (RARE, "Rare"),
        (EPIC, "Epic"),
        (LEGENDARY, "Legendary"),
    )
    name = models.CharField(max_length=200)
    rarity = models.CharField(max_length=1,choices=RARITY_CHOICES,default=COMMON)
    description = models.TextField(max_length=2000)
    value = models.IntegerField(default=100)
    
    def owned_by(self, collector_name):
        print(collector_name)
        return self.collector_set.filter(name=collector_name).exists()

    def __str__(self):
        return self.name

class Collector(models.Model):
    name = models.CharField(max_length=200)
    join_date = models.DateTimeField('join date', default=timezone.now)
    collection = models.ManyToManyField(Card)
    last_collected_coins = models.DateTimeField('latest collection', default=timezone.now)
    coins = models.IntegerField(default=0)

    def get_coins_to_collect(self):
        time_since_last_collection = timezone.now() - self.last_collected_coins
        num_coins = int(time_since_last_collection.total_seconds()/60) #coins gained equivalent to number of minutes since last collection
        
        return num_coins

    def has_card(self, card_name):
        return str(self.collection.filter(name=card_name).exists())
 
    def __str__(self):
        return self.name

collector/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils import timezone

import datetime

from .models import Card,Collector

def get_collector(name):
    try:
        return Collector.objects.get(name=name)
    except Collector.DoesNotExist:
        return Collector.objects.create(name=name)    

# Create your views here.

def index(request):
    context = {
        "cards": Card.objects.all(),
        "collector": get_collector(request.user.username)
    }
    return render(request, "collector/index.html", context)

def card(request,card_id):
    card = get_object_or_404(Card, pk=card_id)
    is_owned = card.owned_by(request.user.username)
    context = {"card":card, "is_owned":is_owned}
    return render(request, "collector/card.html", context)

def buy_pack(request):
    return render(request, "collector/buy_card.html")

def search_results(request):
    search_string = request.POST["search"]
    relevant_cards = Card.objects.filter(name__icontains=search_string)
    collector = get_collector(request.user.username)
    return render(request, "collector/index.html", {"cards": relevant_cards, "collector":collector})
    
def my_collection(request):
    collector = get_collector(request.user.username)
    relevant_cards = collector.collection.all()
    return render(request, "collector/index.html", {"cards": relevant_cards, "collector":collector})
    
def collect(request):
    next = request.POST.get('next',reverse('collector:index'))
    collector = get_collector(request.user.username)
    collector.coins += collector.get_coins_to_collect()
    collector.last_collected_coins = timezone.now()
    collector.save()
    return HttpResponseRedirect(next)
    
def buy_card(request, card_id):
    card = get_object_or_404(Card, pk=card_id)
    collector = get_collector(request.user.username)
    if collector.coins >= card.value:
        collector.collection.add(card)
        collector.coins -= card.value
        collector.save()
        return HttpResponseRedirect(reverse("collector:my_collection"))
    else:
        return HttyResponseRedirect(reverse("collector:card", args=(card_id,)))
        
class NewCardView(LoginRequiredMixin, generic.edit.CreateView):
    model = Card
    fields = ['name','description','rarity']
    template_name = 'collector/new_card.html'
    
      
def create(request):
    name = request.POST['name']
    rarity = request.POST['rarity']
    description = request.POST['description']
    new_card = Card(name=name,description=description,rarity=rarity)
    new_card.save()
    return HttpResponseRedirect(reverse('collector:card', args=(new_card.pk,)))

collector/templates/collector/buy_cards.html
{% extends "base_collect.html" %}

{% block content %}

<div class="container">
    <h1 class="display-4" style="text-align:center">Buy Cards</h1>
    <br />
    <div class="row">
        <div class="col-sm-4">
            <div class="card h-20">
                <div class="card-body">
                    <h5 class="card-title">Buy a Specific Card</h5>
                    <p class="card-text">Know what card you want and have the coins to buy it?</p>
                    <div style="text-align:center">
                        <a href="#" class="btn btn-primary">Buy Specific (100 coins)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Buy a Card Pack</h5>
                    <p class="card-text">Want 5 random cards of varying rarity (may include duplicates)?</p>
                    <div style="text-align:center">
                        <a href="#" class="btn btn-primary">Buy Pack (100 coins)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Buy a Rare Card Pack</h5>
                    <p class="card-text">Want 5 random cards guaranteed to be rare and up?</p>
                    <div style="text-align:center">
                        <a href="#" class="btn btn-primary">Buy Rare Pack (200 coins)</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

collector/templates/collector/buy_pack.html
{% extends "base_collect.html" %}

{% block content %}

<div class="container">
    <h1 class="display-4" style="text-align:center">Buy Cards</h1>
    <br />
    <div class="row">
        <div class="col-sm-4">
            <div class="card h-20">
                <div class="card-body">
                    <h5 class="card-title">Buy a Specific Card</h5>
                    <p class="card-text">Know what card you want and have the coins to buy it?</p>
                    <div style="text-align:center">
                        <a href="#" class="btn btn-primary">Buy Specific (100 coins)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Buy a Card Pack</h5>
                    <p class="card-text">Want 5 random cards of varying rarity (may include duplicates)?</p>
                    <div style="text-align:center">
                        <a href="#" class="btn btn-primary">Buy Pack (100 coins)</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Buy a Rare Card Pack</h5>
                    <p class="card-text">Want 5 random cards guaranteed to be rare and up?</p>
                    <div style="text-align:center">
                        <a href="#" class="btn btn-primary">Buy Rare Pack (200 coins)</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

collector/templates/collector/card.html
{% extends "base_collect.html" %}
{% load collector_extras %}

{% block content %}

{% if card %}
    <div class="container">
        <h1 class="display-4">{{ card.name }}</h1>
        <p>Rarity: {{ card.get_rarity_display }}</p>
        <p>Owned:
            {% if is_owned %}
            Yes
            {% else %}
            No
            <a style="float:right" href="{% url 'collector:buy_card' card.id %}">Buy Card</a>
            {% endif %}
        </p>
        <hr class="my-4">
        <p>{{ card.description }}</p>
    </div>
{% else %}
    <div class="container">
        <p>Couldn't find card.</p>
    </div>
{% endif %}

{% endblock %}

collector/templates/collector/choose_card.html
{% extends "base_collect.html" %}

{% block content %}
{% if cards %}
<div class="container" align="center">
    <table class="table table-sm table-striped fixed-width">
        <thead>
            <th colspan=2><a class="nav-link center" href="{% url 'collector:buy_card' %}">Buy Card ({{ collector.coins }} coins)</a></th>
            <tr>
                <th scope="col">Card Name</th>
                <th scope="col">Card Rarity</th>
            </tr>
        </thead>
        <tbody>
            {% for card in cards %}
                <tr>
                    <td><a href="{% url 'collector:card' card.pk %}">{{ card.name }}</a></td>
                    <td>{{ card.get_rarity_display }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>  
<div>
{% else %}
    <p style="text-align:center"> No Cards are available.</p>
{% endif %}
{% endblock %}

collector/templates/collector/index.html
{% extends "base_collect.html" %}
{% load collector_extras %}

{% block content %}
{% if cards %}
<div class="container" align="center">
    <table class="table table-sm table-striped fixed-width">
        <thead>
            <th colspan=4><a class="nav-link center" href="{% url 'collector:buy_pack' %}">Buy Pack ({{ collector.coins }} coins)</a></th>
            <tr>
                <th scope="col">Card Name</th>
                <th scope="col">Card Rarity</th>
                <th scope="col">Card Description</th>
                <th scope="col">Owned</th>
            </tr>
        </thead>
        <tbody>
            {% for card in cards %}
                <tr>
                    <td><a href="{% url 'collector:card' card.pk %}">{{ card.name }}</a></td>
                    <td>{{ card.get_rarity_display }}</td>
                    <td>{{ card.description|truncatechars:25 }}</td>
                    <td>{% call_method card "owned_by" user.username %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>  
<div>
{% else %}
    <p style="text-align:center"> No Cards are available.</p>
{% endif %}
{% endblock %}

collector/templates/collector/new_card.html
{% extends "base_generic.html" %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">
    <form action="{% url 'collector:create' %}" method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="name">{{ form.name.label_tag }}</label>
            <input type="text" name="name" class="form-control" placeholder="Enter Card Name..."/>
        </div>
        <div class="form_group">
            <label for="rarity">{{ form.rarity.label_tag }}</label>
            <select class="custom-select" name="rarity">
                {% for choice in form.rarity.field.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>
        <br />
        <div class="form_group">
            <label for="description">{{ form.description.label_tag }}</label>
            <textarea type="text" name="description" class="form-control" placeholder="Enter Card Description..."></textarea>
        </div>
        <br />
        <div style="text-align:center;">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>
</div>
{% endblock %}