blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:post_id>/', views.blogpost, name='blogpost'),
    path('<int:pk>/edit/', views.EditPostView.as_view(), name='edit'),
    path('new/', views.NewPostView.as_view(), name='new'),
    path('<int:post_id>/change/', views.change, name='change'),
    path('create/', views.create, name='create'),
    path('search_results/', views.search_results, name='search_results'),
    path('myposts/', views.OwnedPostsByUserView.as_view(), name='myposts'),
    path('mycomments/', views.OwnedCommentsByUserView.as_view(), name='mycomments'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/deleted/', views.deleted, name='deleted'),
    path('<int:comment_id>/editcomment/', views.edit_comment, name='editcomment'),
    path('<int:comment_id>/deletedcomment/', views.deleted_comment, name='deletedcomment'),
    
    
]

mysite/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin

app_name = "polls"
urlpatterns = [
    path('', include("blog.urls")),
    path('polls/', include("polls.urls")),
    path('collector/', include("collector.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=200)
    join_date = models.DateTimeField('join date', default=timezone.now)
    
    def joined_recently(self):
        now = timezone.now()
        return now >= self.join_date >= now - datetime.timedelta(days=30)
    
    def __str__(self):
        return self.name
        
    joined_recently.admin_order_field = 'join_date'
    joined_recently.boolean = True
    joined_recently.short_description = 'Joined recently?'

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField(max_length=2000)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    
    def was_published_today(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
        
    def format_published(self): 
        if self.was_published_today():
            return "at " + self.pub_date.strftime("%H:%M")
        
        return "on " + self.pub_date.strftime("%d/%m/%y")
        
    def __str__(self):
        return self.title
        
    was_published_today.admin_order_field = 'pub_date'
    was_published_today.boolean = True
    was_published_today.short_description = 'Published recently?'
        
class Comment(models.Model):
    body = models.TextField(max_length=2000)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    
    def was_published_today(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)
        
    def format_published(self): 
        print()
        if self.was_published_today():
            return "at " + self.pub_date.strftime("%H:%M")
        
        return "on " + self.pub_date.strftime("%d/%m/%y")
        
    def __str__(self):
        return "Comment on: " + self.post.title

blog/forms.py
from django import forms

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Author, BlogPost, Comment

import markdown

def get_author(name):
    try:
        author = Author.objects.all().get(name=name)
    except Author.DoesNotExist:
        author = Author.objects.create(name=name)

    return author

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'blogposts'
    
    def get_queryset(self):
        """return the 10 last published blogposts won't include those set to be published in the future"""
        return BlogPost.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:10]     

def search_results(request):
    search_string = request.POST["search"]
    q1 = BlogPost.objects.filter(body__icontains=search_string,pub_date__lte=timezone.now())
    q2 = BlogPost.objects.filter(title__icontains=search_string,pub_date__lte=timezone.now())
    relevant_posts = q1.union(q2).order_by("-pub_date")
    return render(request, "blog/index.html", {"blogposts": relevant_posts})

def blogpost(request, post_id):
    queryset = BlogPost.objects.filter(pub_date__lte=timezone.now())
    blogpost = get_object_or_404(queryset,pk=post_id)
    print(blogpost.comment_set.all())
    comments = blogpost.comment_set.all().order_by("pub_date")
    return render(request, "blog/post.html", {"blogpost": blogpost, "body": markdown.markdown(blogpost.body), "comments":comments})

def deleted(request, post_id):
    blogpost = get_object_or_404(BlogPost,pk=post_id)
    print(blogpost.author.name, request.user.username)
    if blogpost.author.name == request.user.username:
        print("hmm")
        title = blogpost.title
        body = blogpost.body
        blogpost.delete()
        return render(request, "blog/deleted.html", {"title": title,"body": body})
    else:
        return HttpResponseRedirect(reverse('blog:blogpost', args=(post_id,)))


class EditPostView(LoginRequiredMixin, generic.edit.UpdateView):
    model = BlogPost
    fields = ['title','body']
    template_name = 'blog/edit.html'

class NewPostView(LoginRequiredMixin, generic.edit.CreateView):
    model = BlogPost
    fields = ['title','body']
    template_name = 'blog/new.html'

def change(request, post_id):
    blogpost = get_object_or_404(BlogPost, pk=post_id)
    blogpost.title = request.POST['title']
    blogpost.body = request.POST['body']
    blogpost.pub_date = timezone.now()
    blogpost.save()
    return HttpResponseRedirect(reverse('blog:blogpost', args=(post_id,)))


class OwnedPostsByUserView(LoginRequiredMixin,generic.ListView):
    template_name = 'blog/ownposts.html'
    context_object_name = 'blogposts'
    
    def get_queryset(self):
        author = get_author(self.request.user.username)
        return author.blogpost_set.all().order_by("-pub_date")
        

class OwnedCommentsByUserView(LoginRequiredMixin,generic.ListView):
    template_name = 'blog/owncomments.html'
    context_object_name = 'comments'
    
    def get_queryset(self):
        author = get_author(self.request.user.username)
        print(author.comment_set.all()[1].post.id)
        return author.comment_set.all().order_by("-pub_date")
    
    
def create(request):
    title = request.POST['title']
    body = request.POST['body']
    pub_date = timezone.now()
    author = get_author(request.user.username)
    new_post = BlogPost(title=title,body=body,author=author)
    new_post.save()
    return HttpResponseRedirect(reverse('blog:blogpost', args=(new_post.pk,)))
    
def comment(request, post_id):
    body = request.POST['body']
    pub_date = timezone.now()
    blogpost = get_object_or_404(BlogPost, pk=post_id)
    author = get_author(request.user.username)
    new_comment = Comment(body=body, pub_date=pub_date, author=author, post=blogpost)
    new_comment.save()
    return HttpResponseRedirect(reverse('blog:blogpost', args=(post_id,)))
    
def edit_comment(request,comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.body = request.POST['body']
    comment.save()
    return HttpResponseRedirect(reverse('blog:blogpost', args=(comment.post.id,)))
    
def deleted_comment(request, comment_id):
    comment = get_object_or_404(Comment,pk=comment_id)
    if comment.author.name == request.user.username:
        comment.delete()        
    return HttpResponseRedirect(reverse('blog:blogpost', args=(comment.post.id,)))

blog/templates/blog/delete.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <p>post {{ blogpost.title }} has been deleted.</p>
    <form action="{% url 'blog:create' %}" method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="title">{{ form.title.label_tag }}</label>
            <input type="hidden" name="title" class="form-control" value="{{ blogpost.title }}"/>
        </div>
        <div class="form_group">
            <label for="body">{{ form.body.label_tag }}</label>
            <textarea type="hidden" name="body" class="form-control">{{ blogpost.body }}<textarea>
        </div>
        <br />
        <div style="text-align:center;">
            <button type="submit" class="btn btn-link">undo</button>
        </div>
    </form>
    

{% endblock %}

blog/templates/blog/deleted.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <div class="alert alert-secondary" role="alert">
        <p style="text-align:center">post "{{ title }}" has been deleted.</p>
    </div>
    <form action="{% url 'blog:create' %}" method="post">
    {% csrf_token %}
        <div style="text-align:center;">
            <button type="submit" class="btn btn-link">undo</button>
        </div>
        <div class="form-group">
            <input type="hidden" name="title" class="form-control" value="{{ title }}"/>
        </div>
        <div class="form_group">
            <input type="hidden" name="body" class="form-control" value="{{ body }}" />
        </div>
        <br />
    </form>
</div>
{% endblock %}

blog/templates/blog/deletedcomment.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <div class="alert alert-secondary" role="alert">
        <p style="text-align:center">post "{{ title }}" has been deleted.</p>
    </div>
    <form action="{% url 'blog:comment' comment.id%}" method="post">
    {% csrf_token %}
        <div style="text-align:center;">
            <button type="submit" class="btn btn-link">undo</button>
        </div>
        <div class="form-group">
            <input type="hidden" name="body" class="form-control" value="{{ body }}"/>
        </div>
        <br />
    </form>
</div>
{% endblock %}

blog/templates/blog/edit.html
{% extends "base_generic.html" %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block content %}
{% if user.is_authenticated %}
    {% if user.username == blogpost.author.name %}
        <div class="container">
            <form action="{% url 'blog:change' blogpost.id %}" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <label for="title">{{ form.title.label_tag }}</label>
                    <input type="text" name="title" class="form-control" value="{{ form.title.value }}" />
                </div>
                <div class="form_group">
                    <label for="body">{{ form.body.label_tag }}</label>
                    <textarea type="text" name="body" class="form-control">{{ form.body.value }}</textarea>
                </div>
                <br />
                <div style="text-align:center;">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    {% else %}
        <div class="container">
            <div class="alert alert-secondary" role="alert">
                <p style="text-align:center">You don't have permission to edit this post.</p>
            </div>
        </div>
    {% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/editcomment.html
{% extends "base_generic.html" %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% block content %}
{% if user.is_authenticated %}
    {% if user.username == comment.author.name %}
        <div class="container">
            <form action="{% url 'blog:editcomment' comment.id %}" method="post">
            {% csrf_token %}
                <div class="form_group">
                    <label for="body">Comment:</label>
                    <textarea type="text" name="body" class="form-control">{{ form.body.value }}</textarea>
                </div>
                <br />
                <div style="text-align:center;">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    {% else %}
        <div class="container">
            <div class="alert alert-secondary" role="alert">
                <p style="text-align:center">You don't have permission to edit this comment.</p>
            </div>
        </div>
    {% endif %}
{% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends "base_generic.html" %}

{% block content %}
{% if blogposts %}
<div class="container" align="center">
    <table class="table table-sm table-striped fixed-width">
        <thead>
            <th colspan=3><a class="nav-link center" href="{% url 'blog:new' %}">+ new post</a></th>
            <tr>
                <th scope="col">Post Title</th>
                <th scope="col">Author</th>
                <th scope="col">Last Edited</th>
            </tr>
        </thead>
        <tbody>
            {% for blogpost in blogposts %}
                <tr>
                    <td><a href="{% url 'blog:blogpost' blogpost.pk %}">{{ blogpost.title }}</a></td>
                    <td>{{ blogpost.author }}</td>
                    <td>{{ blogpost.pub_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>  
<div>
{% else %}
    <p style="text-align:center"> No blogposts are available.</p>
{% endif %}
{% endblock %}

blog/templates/blog/new.html
{% extends "base_generic.html" %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">
    <form action="{% url 'blog:create' %}" method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="title">{{ form.title.label_tag }}</label>
            <input type="text" name="title" class="form-control" placeholder="Enter Title"/>
        </div>
        <div class="form_group">
            <label for="body">{{ form.body.label_tag }}</label>
            <textarea type="text" name="body" class="form-control" placeholder="Enter Body..."></textarea>
        </div>
        <br />
        <div style="text-align:center;">
            <button type="submit" class="btn btn-primary">Post</button>
        </div>
    </form>
</div>
{% endblock %}

blog/templates/blog/owncomments.html
{% extends "base_generic.html" %}

{% block content %}
{% if comments %}
<div class="container" align="center">
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th scope="col">Post Title</th>
                <th scope="col">Comment</th>
                <th scope="col">Commented</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for comment in comments %}
                <tr>
                    <td><a href="{% url 'blog:blogpost' comment.post.id %}">{{ comment.post.title }}</a></td>
                    <td>{{ comment.body | truncatechars:50 }}</td>
                    <td>{{ comment.pub_date }}</td>                    
                    <td><a href="{% url 'blog:editcomment' comment.pk %}">edit</a></td>
                    <td><a href="{% url 'blog:deletedcomment' comment.pk %}">delete</a></td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>  
<div>
{% else %}
    <p style="text-align:center"> You haven't commented on any posts.</p>
{% endif %}
{% endblock %}

blog/templates/blog/ownposts.html
{% extends "base_generic.html" %}

{% block content %}
{% if blogposts %}
<div class="container" align="center">
    <table class="table table-sm table-striped">
        <thead>
            <th colspan=4><a class="nav-link center" href="{% url 'blog:new' %}">+ new post</a></th>
            <tr>
                <th scope="col">Post Title</th>
                <th scope="col">Last Edited</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for blogpost in blogposts %}
                <tr>
                    <td><a href="{% url 'blog:blogpost' blogpost.pk %}">{{ blogpost.title }}</a></td>
                    <td>{{ blogpost.pub_date }}</td>                    
                    <td><a href="{% url 'blog:edit' blogpost.pk %}">edit</a></td>
                    <td><a href="{% url 'blog:deleted' blogpost.pk %}">delete</a></td>
                    
                </tr>
            {% endfor %}
        </tbody>
    </table>  
<div>
{% else %}
    <p style="text-align:center"> No blogposts are available.</p>
{% endif %}
{% endblock %}

blog/templates/blog/post.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h1 class="display-4">{{ blogpost.title }}</h1>
    <p>Posted by {{ blogpost.author.name }} last edited {{ blogpost.format_published }}</p>
    <hr class="my-4">
    <p>{{ body | safe }}</p>
    <hr class="my-4">
</div>
<div class="container">
    <h3>
    Comments:
    <button style="float:right" class="btn btn-link" type="button" data-toggle="collapse" data-target="#addcomment" aria-expanded="false" aria-controls="collapseExample">
        Add comment
    </button>
    </h3>
    <div class="collapse" id="addcomment">
        <div class="card card-body">
            <form action="{% url 'blog:comment' blogpost.id %}" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">Enter Comment:</label>
                    <textarea type="text" name="body" class="form-control" placeholder="Comment..."></textarea>
                </div>
                <br />
                <div style="text-align:center;">
                    <button type="submit" class="btn btn-primary">Comment</button>
                </div>
            </form>
        </div>
    </div>
    {% for comment in comments %}
    <hr class="my-4">
    <p>{{ comment.body }}</p>
    {% if user.is_authenticated %}
        {% if user.username == comment.author.name %}
            <p>Posted by You ({{ comment.format_published }})</p>
            <!-- edit and delete links -->    
            <p>
                <a class="btn btn-link" data-toggle="collapse" href="#editcomment{{ comment.id }}" role="button" aria-expanded="false" aria-controls="editcomment{{ comment.id }}">edit</a> | 
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#deletecomment{{ comment.id }}" aria-expanded="false" aria-controls="deletecomment{{ comment.id }}">delete</button>
            </p>
            <div class="collapse" id="editcomment{{ comment.id }}">
                <div class="card card-body" style="border:none;">
                    <div class="container">
                        <form action="{% url 'blog:editcomment' comment.id %}" method="post">
                            {% csrf_token %}
                            <div class="form_group">
                                <label for="body">Comment:</label>
                                <textarea rows=5 type="text" name="body" class="form-control">{{ comment.body }}</textarea>
                            </div>
                            <br />
                            <div style="text-align:center;">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="collapse" id="deletecomment{{ comment.id }}">
                <div class="card card-body" style="border:none;">
                    <form action="{% url 'blog:deletedcomment' comment.id %}" method="post">
                        {% csrf_token %}
                        <div style="text-align:center;">
                            <button type="submit" class="btn btn-danger">Delete Comment</button>
                        </div>
                    </form>
                </div>
            </div>
        {% else %}
            <p>Posted by {{ comment.author }} ({{ comment.format_published }})</p>
        {% endif %}
    {% endif %}
    {% endfor %}
</div>
{% endblock %}