blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:post_id>/', views.blogpost, name='blogpost'),
    path('<int:pk>/edit/', views.EditPostView.as_view(), name='edit'),
    path('new/', views.NewPostView.as_view(), name='new'),
    path('<int:post_id>/change/', views.change, name='change'),
    path('create/', views.create, name='create'),
    path('search_results/', views.search_results, name='search_results'),
    path('myposts/', views.OwnedPostsByUserView.as_view(), name='myposts'),
    path('mycomments/', views.OwnedCommentsByUserView.as_view(), name='mycomments'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/deleted/', views.deleted, name='deleted'),
    path('<int:comment_id>/editcomment/', views.edit_comment, name='editcomment'),
    path('<int:comment_id>/deletedcomment/', views.deleted_comment, name='deletedcomment'),
    
    
]

collector/urls.py
from django.urls import path

from . import views

app_name = "collector"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:card_id>/', views.card, name='card'),
    path('buy_card/<int:card_id>', views.buy_card, name="buy_card"),
    path('buy_pack/', views.buy_pack, name="buy_pack"),
    path('search_results/', views.search_results, name="search_results"),
    path('my_collection/', views.my_collection, name="my_collection"),
    path('new_card/', views.NewCardView.as_view(), name="new_card"),
    path('create/', views.create, name='create'),
    path('collect/', views.collect, name="collect"),
]

mysite/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin

app_name = "polls"
urlpatterns = [
    path('', include("blog.urls")),
    path('polls/', include("polls.urls")),
    path('collector/', include("collector.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

templates/base_collect.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Collect-a-thon</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>

<body>
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Collect-a-thon</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'collector:index' %}">Home</a>
            </li>
            <li class="nav-item active">
                <form action="{% url 'collector:collect'%}">
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button type="submit" class="btn btn-link">Collect Coins</button>
                </form>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'collector:search_results' %}" method="post">
            {% csrf_token %}
            <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Card search</button>
        </form>
        </div>
        {% if user.is_authenticated %}
            <div class="dropdown show">
                <a class="btn btn-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{user.username}}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'collector:buy_pack' %}">Buy Pack ({{ collector.coins }} coins)</a>
                    <a class="dropdown-item" href="{% url 'collector:my_collection' %}">View Collection</a>
                    <a class="dropdown-item" href="{% url 'collector:new_card' %}">Create Card</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {% else %}
        <a class="nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</nav>
<br />
<br />
{% endblock %}

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Blog N' Poll</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>

<body>
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">BlogSite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'blog:search_results' %}" method="post">
            {% csrf_token %}
            <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">blogpost search</button>
        </form>
        </div>
        {% if user.is_authenticated %}
            <div class="dropdown show">
                <a class="btn btn-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{user.username}}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'blog:new' %}">+ New Post</a>
                    <a class="dropdown-item" href="{% url 'blog:myposts' %}">My Posts</a>
                    <a class="dropdown-item" href="{% url 'blog:mycomments' %}">My Comments</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {% else %}
        <a class="nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</nav>
<br />
<br />
{% endblock %}

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>